# Generated by Django 3.2.8 on 2021-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='long_url',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
